# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptops', '0003_user_end_date_user_end_time_user_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(
                choices=[
                    ('yet_to_join', 'Yet to Join'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('not_joined', 'Not Joined'),
                    ('discontinued', 'Discontinued'),
                    ('on_hold', 'On Hold'),
                ],
                default='yet_to_join',
                max_length=20,
            ),
        ),
    ]
